from __future__ import annotations
import pathlib

import numpy as np
import zarr
from zarr import Array, Group

from .prep import prep


def load_or_prep(data_path: str | pathlib.Path,
                 max_wavs: int = 120,
                 max_num_psds: int = 10000,
                 ) -> np.ndarray:
    """Either load an array of PSDs from a .zarr file,
    or prepare the PSDs from a directory of .wav files.

    Parameters
    ----------
    data_path : str or pathlib.Path
        Either a path to a directory with .wav files of songs,
        or a path to a .songdkl.zarr file generated by songdkl prep.
    max_wavs : int
        Maximum number of wav files to use. Default is 120.
    max_num_psds : int
        Maximum number of power spectral densities (PSDs) to calculate.
        Default is 10000.

    Returns
    -------
    segedpsds : numpy.ndarray
        Array with PSDs from syllable segments.
    """
    data_path = pathlib.Path(data_path)
    if data_path.suffix == '.zarr':
        segedpsds = load(zarr_path=data_path)
    elif data_path.is_dir():
        segedpsds = prep(data_path, max_wavs, max_num_psds)
    else:
        raise ValueError(
            f'Not recognized as a .zarr file or a directory: {data_path}'
        )
    return segedpsds


def load(zarr_path: str | pathlib.Path) -> Array | Group:
    """Load an array saved in a .zarr file.

    Parameters
    ----------
    zarr_path : str, pathlib.Path
        Path to a file with extension .zarr,
        saved by ``songdkl.prep_and_save``

    Returns
    -------
    segedpsds : numpy.ndarray
        Array with PSDs from syllable segments.
    """
    return zarr.load(zarr_path)
